language: ruby
cache: bundler
sudo: false
rvm: 2.4.0
matrix:
  include:
    - rvm: 2.3.3
      env: "RAILS_VERSION=4.2.7.1"
    - env: "RSOLR_VERSION=2.0.0.pre1"
global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
  - gem update --system
before_script:
  - jdk_switcher use oraclejdk8
